stopwatch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('timeclock.urls', namespace='timeclock')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

timeclock/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', login_required(views.ClockInOutView.as_view()), name="clockinout"),
    url(r'^timecards/$', login_required(views.PunchList.as_view()), name="timecards"),
    #url(r'^punchform/$', login_required(views.SearchForm.as_view()), name="punchform"),
]

timeclock/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

def chop_microseconds(delta):
        return delta - datetime.timedelta(microseconds=delta.microseconds)

class Project(models.Model):
    title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.title

class Punch(models.Model):
    user     = models.ForeignKey(User)
    project  = models.ForeignKey(Project)
    time_in  = models.DateTimeField(auto_now_add=True)
    time_out = models.DateTimeField(blank=True, null=True)
    note     = models.CharField(max_length=200, blank=True, null=True)

    def is_clocked_in(self):
        if self.time_out == None:
            return True
        return False

    def duration(self):
        if self.time_out and self.time_in:
            return chop_microseconds(self.time_out - self.time_in)
        else:
            return chop_microseconds(datetime.timedelta())

    def __unicode__(self):
        return "%s (in: %s, out: %s, dur: %s)" % (self.user.username, str(self.time_in), str(self.time_out), str(self.duration()))

    class Meta:
        verbose_name_plural = "punches"

timeclock/forms.py
from django import forms
from .models import Project

class PunchInForm(forms.Form):
    project = forms.ModelChoiceField(queryset = Project.objects.all())

class PunchOutForm(forms.Form):
    note = forms.CharField()

class PunchByDateForm(forms.Form):
    #projects = forms.ModelChoiceField(queryset = Project.objects.all())
    start_date = forms.DateField()
    end_date = forms.DateField()

timeclock/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import FormView, ListView, DetailView, View
from django.views.generic.detail import SingleObjectMixin
from django.utils import timezone
from django.http import HttpResponseRedirect
import datetime

from .forms import PunchInForm, PunchOutForm, PunchByDateForm
from django.contrib.auth.models import User
from .models import Project, Punch

class ClockInOutView(FormView):
    success_url = reverse_lazy('timeclock:clockinout')
    def get_template_names(self):
        template_name = 'timeclock/home_clockin.html'
        records = self.request.user.punch_set.order_by('-time_in')
        if records:
            if records[0].is_clocked_in():
                template_name = 'timeclock/home_clockout.html'

        return [template_name]

    def get_form_class(self):
        records = self.request.user.punch_set.order_by('-time_in')
        if records:
            if records[0].is_clocked_in():
                return PunchOutForm

        return PunchInForm

    def get_context_data(self, **kwargs):
        context = super(ClockInOutView, self).get_context_data(**kwargs)

        objects = Punch.objects.filter(user = self.request.user).order_by('time_in')
        if objects:
            context["last_punch"] = objects[0]
        else:
            context["last_punch"] = None

        return context

    def form_valid(self, form):
        if type(form).__name__ == 'PunchInForm':
            entry = Punch()
            entry.project = form.cleaned_data['project']
            entry.user = self.request.user
            entry.save()
            #return HttpResponseRedirect(reverse('timeclock:clockinout'))

        if type(form).__name__ == 'PunchOutForm':
            entry = self.request.user.punch_set.order_by('-time_in')[0]
            entry.note = form.cleaned_data['note']
            entry.time_out = timezone.now()
            entry.save()
            #return HttpResponseRedirect(reverse('timeclock:clockinout'))

        return super(ClockInOutView, self).form_valid(form)

#class PunchByDateList(ListView):
#    model = Punch
#
#    def get_context_data(self, **kwargs):
#        context = super(PunchByDateList, self).get_context_data(**kwargs)
#        context['form'] = PunchByDateForm()
#
#class SearchByDateForm(SingleObjectMixin, FormView):
#    template_name = 'timeclock/punch_list.html'
#    form_class = PunchByDateForm
#    model = Punch
#
#    def post(self, request, *args, **kwargs):
#        self.object = self.get_object()
#        return super(SearchByDateForm, self).post(request, *args, **kwargs)
#
#    def get_success_url(self):
#        return reverse('timeclock:punchlist')
#
#    def form_valid(self, form):
#        form.cleaned_data['filter_by']
#        form.cleaned_data['state_date']
#        form.cleaned_data['end_date']
#
#        return super(SearchByDataForm, self).form_valid(self, form)
#
#class SearchForm(FormView):
#    model = Punch
#    form_class = PunchByDateForm
#    success_url = reverse_lazy('timeclock:clockinout')
#
#    def post(self, request, *args, **kwargs):
#        self.object = self.get_object()
#        return super(SearchByDateForm, self).post(request, *args, **kwargs)
#
#    def form_valid(self, form):
#        form.cleaned_data['filter_by']
#        form.cleaned_data['state_date']
#        form.cleaned_data['end_date']
#
#        return super(SearchByDataForm, self).form_valid(self, form)
#
#
#class PunchList(View):
#    template_name = 'timeclock/punch_form.html'
#
#    def get(self, request, *args, **kwargs):
#        view = PunchByDateList.as_view()
#        return view(request, *args, **kwargs)
#
#    def post(self, request, *args, **kwargs):
#        view = SearchByDateForm.as_view()
#        return view(request, *args, **kwargs)

class PunchList(ListView):
    model = Punch
    form_class = PunchByDateForm
    paginate_by = 10

    def get_queryset(self):
        #get_punches = self.request.user.punch_set.all()
        get_punches = Punch.objects.filter(user = self.request.user)

        if self.request.user.is_superuser:
            get_punches = Punch.objects.all()

        if self.request.user.is_superuser and self.request.GET.get('user'):
            get_punches = get_punches.filter(user = self.request.GET.get('user'))

        if self.request.GET.get('project'):
            get_punches = get_punches.filter(project = self.request.GET.get('project'))

        print self.request.GET.get('start_date')
        if self.request.GET.get('start_date'):
            get_punches = get_punches.filter(time_in__gte = self.request.GET.get('start_date'))

        print self.request.GET.get('end_date')
        if self.request.GET.get('end_date'):
            d = datetime.datetime.strptime(self.request.GET.get("end_date"), "%Y-%m-%d")
            d = d + datetime.timedelta(days = 1)
            get_punches = get_punches.filter(time_in__lte = d)

        return get_punches.order_by('-time_in')

    def get_context_data(self, **kwargs):
        context = super(PunchList, self).get_context_data(**kwargs)

        #Add all projects to the template's context to the template's context
        context["projects"] = Project.objects.all().order_by('title')
        context["users"] = User.objects.all().order_by('first_name')

        #Get all objects for the current query
        queryset = self.get_queryset()

        total_time = datetime.timedelta(0)
        for punch in queryset:
            total_time += punch.duration()

        context["total_time"] = total_time

        return context

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Time Clock{% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

      <!-- Custom Css -->
      {% load staticfiles %}
      <link rel="stylesheet" type="text/css" href="{% static 'timeclock/css/styles.css' %}">

      <!-- Google Fonts -->
      <link href='https://fonts.googleapis.com/css?family=Allura|Vollkorn' rel='stylesheet' type='text/css'>

      <!-- Extra Script -->
      {% block extrascripts %}{% endblock %}
    </head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <div class="clock-brand">
          <a class="navbar-brand" href="/">Time Clock</a>
          <img class="timer-img" src="{% static 'timeclock/img/clock.png' %}" alt="time clock">
        </div>
      </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      {% if request.user.is_authenticated %}
      <li><a href="{% url 'timeclock:clockinout' %}"><span class="glyphicon glyphicon-hourglass"></span> Timer</a></li>
      <li><a href="{% url 'timeclock:timecards' %}?&page=1"><span class="glyphicon glyphicon-time"></span> Time Cards</a></li>
      {% endif %}
      </ul>

      <ul class="nav navbar-nav navbar-right">
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'auth_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
      {% else %}
        <li><a href="{% url 'registration_register' %}"><span class="glyphicon glyphicon-edit"></span> Create Account</a></li>
        <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
      {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container content">
{% block content %}

    <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
{% endblock %}
  </div><!-- End of Container -->

  <footer>
    <div class="container">
      <p>Copyright &copy; 2015 Timeclock</p>
    </div>
  <footer>

  </body>
</html>

timeclock/templates/timeclock/home_clockin.html
{% extends 'base.html' %}

{% block title %}Clock In{% endblock %}

{% block content %}

<div class="clockinout">
  <h1>Clock In</h1>
  <form action="." method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-default">Clock In!</button>
  </form>
</div>

{% endblock %}

timeclock/templates/timeclock/home_clockout.html
{% extends 'base.html' %}

{% block title %}Clock Out{% endblock %}

{% block content %}

<div class="clockinout">
  <h1>Clock Out</h1>
  <div class="timer">
      <label id="hours">00</label>:<label id="minutes">00</label>:<label id="seconds">00</label>
  </div>
  <script>
      // Thanks to http://stackoverflow.com/questions/5517597/plain-count-up-timer-in-javascript
      // and http://stackoverflow.com/questions/1259219/django-datefield-to-unix-timestamp
      var sec = Math.floor(new Date().getTime() / 1000) - {{ last_punch.time_in|date:"U" }};
      function pad ( val ) { return val > 9 ? val : "0" + val; }
      setInterval( function(){
          $("#seconds").html(pad(++sec % 60));
          $("#minutes").html(pad(parseInt(sec/60,10) % 60));
          $("#hours").html(pad(parseInt(sec / 60 / 60, 10)));
      }, 1000);
  </script>
  <form action="." method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-default">Clock Out!</button>
  </form>
</div>

{% endblock %}

timeclock/templates/timeclock/punch_form.html
{% extends 'base.html' %}

{% block title %}List of Punches by Date{% endblock %}

{% block content %}

<h1>View Punches by Date</h1>
<form action="." method="post">
  {% csrf_token %}
  {{ form }}
  <button class="btn btn-default">Search</button>
</form>

{% endblock %}

timeclock/templates/timeclock/punch_list.html
{% extends 'base.html' %}

{% block title %}List of Punches by Date{% endblock %}

{% block content %}

<h2>Filter Time Cards</h2>
<form action="." method="GET">
  {% if request.user.is_superuser %}
  <select name="user">
    <option value="">All Users</option>
    {% for user in users %}
      <option value="{{ user.id }}">{% if user.first_name %} {{ user.first_name}} {% else %} {{ user.username }} {% endif %}</option>
    {% endfor %}
  </select>
  {% endif %}
  <select name="project">
    <option value="">All Projects</option>
    {% for project in projects %}
      <option value="{{ project.id }}">{{ project.title }}</option>
    {% endfor %}
  </select>
  <input type="date" name="start_date">
  <input type="date" name="end_date">
  <!--
  <input type="date" name="start_date" data-date-format="yyyy-m-dd">
  <input type="date" name="end_date" data-date-format="yyyy-m-dd">
-->
  <input type="hidden" name="page" value="1">
  <button class="btn btn-default">Search</button>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Project</th>
            <th>Note</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
        </tr>
      </thead>
      <tbody>
      {% for punch in punch_list %}
        <tr>
            <td>{% if punch.user.first_name %} {{ punch.user.first_name}} {% else %} {{ punch.user.username }} {% endif %}</td>
            <td>{{ punch.project.title }}</td>
            <td>{{ punch.note }}</td>
            <td>{{ punch.time_in }}</td>
            <td>{{ punch.time_out }}</td>
            <td>{{ punch.duration }}</td>
        </tr>
      {% empty %}
          <p>The form above needs to be sumbited before any results will show.</p>
      {% endfor %}
            </tbody>
      </table>

      {% if punch_list %}
        <p id="total">Total Time: {{ total_time }}</p>
      {% endif %}

<!-- Pagination goes here -->
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a class="btn btn-pg previous" href="{{ request.get_full_path|slice:":-7" }}&page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a class="btn btn-pg next" href="{{ request.get_full_path|slice:":-7" }}&page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}

{% endblock %}